version: '3.8'

services:
  powerautomation-frontend:
    build: 
      context: ./claudeditor
      dockerfile: Dockerfile
    container_name: powerauto-frontend
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=https://powerauto.ai/api
      - NEXT_PUBLIC_CORE_URL=https://powerauto.ai/core
      - PORT=3000
    volumes:
      - ./claudeditor/uploads:/app/uploads
    networks:
      - powerauto-network

  membership-api:
    build: 
      context: .
      dockerfile: Dockerfile.membership
    container_name: powerauto-membership
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - DATABASE_URL=sqlite:///data/powerautomation.db
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - PORT=8082
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    networks:
      - powerauto-network

  powerautomation-core:
    build:
      context: .
      dockerfile: Dockerfile.core
    container_name: powerauto-core
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - CLAUDE_API_KEY=${CLAUDE_API_KEY}
      - KIMI_API_KEY=${KIMI_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - HUGGINGFACE_API_KEY=${HUGGINGFACE_API_KEY}
      - PORT=8080
      - WEBSOCKET_PORT=8081
    volumes:
      - ./core/data:/app/data
      - ./logs:/app/logs
    networks:
      - powerauto-network
    depends_on:
      - membership-api

  nginx:
    image: nginx:alpine
    container_name: powerauto-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - powerautomation-frontend
      - membership-api
      - powerautomation-core
    networks:
      - powerauto-network

networks:
  powerauto-network:
    driver: bridge

volumes:
  powerauto-data:
  powerauto-logs: