#!/bin/bash
# PowerAutomation v4.71 Memory RAG Edition 环境变量模板

# 版本信息
export POWERAUTOMATION_VERSION="4.71"
export POWERAUTOMATION_EDITION="Memory RAG Edition"
export POWERAUTOMATION_RELEASE_DATE="2025-01-17"

# 必需配置 (用户需要设置)
export HF_TOKEN="${HF_TOKEN:-demo-token}"
export ANTHROPIC_API_KEY="${ANTHROPIC_API_KEY:-}"

# 可选配置 (AWS S3 支持)
export AWS_ACCESS_KEY_ID="${AWS_ACCESS_KEY_ID:-}"
export AWS_SECRET_ACCESS_KEY="${AWS_SECRET_ACCESS_KEY:-}"
export AWS_DEFAULT_REGION="${AWS_DEFAULT_REGION:-us-east-1}"

# 路径配置
export POWERAUTOMATION_HOME="$HOME/.powerautomation"
export POWERAUTOMATION_CONFIG_DIR="$POWERAUTOMATION_HOME/config"
export POWERAUTOMATION_DATA_DIR="$POWERAUTOMATION_HOME/data"
export POWERAUTOMATION_LOGS_DIR="$POWERAUTOMATION_HOME/logs"
export POWERAUTOMATION_CACHE_DIR="$POWERAUTOMATION_HOME/cache"

# Python 路径配置
export PYTHONPATH="$POWERAUTOMATION_HOME/aicore0716:$PYTHONPATH"

# Memory RAG 配置
export MEMORY_RAG_CONFIG="$POWERAUTOMATION_CONFIG_DIR/memory_rag_config.json"
export MEMORY_RAG_DATA_DIR="$POWERAUTOMATION_DATA_DIR"
export MEMORY_RAG_LOGS_DIR="$POWERAUTOMATION_LOGS_DIR"
export MEMORY_RAG_CACHE_DIR="$POWERAUTOMATION_CACHE_DIR"

# 服务配置
export MEMORY_RAG_HOST="${MEMORY_RAG_HOST:-127.0.0.1}"
export MEMORY_RAG_PORT="${MEMORY_RAG_PORT:-8080}"
export MEMORY_RAG_WORKERS="${MEMORY_RAG_WORKERS:-4}"

# 性能配置
export MEMORY_RAG_MAX_WORKERS="${MEMORY_RAG_MAX_WORKERS:-4}"
export MEMORY_RAG_CACHE_SIZE="${MEMORY_RAG_CACHE_SIZE:-1000}"
export MEMORY_RAG_BATCH_SIZE="${MEMORY_RAG_BATCH_SIZE:-32}"
export MEMORY_RAG_TIMEOUT="${MEMORY_RAG_TIMEOUT:-30}"

# 安全配置
export MEMORY_RAG_API_KEY="${MEMORY_RAG_API_KEY:-}"
export MEMORY_RAG_RATE_LIMIT="${MEMORY_RAG_RATE_LIMIT:-100}"

# 调试配置
export MEMORY_RAG_DEBUG="${MEMORY_RAG_DEBUG:-false}"
export MEMORY_RAG_LOG_LEVEL="${MEMORY_RAG_LOG_LEVEL:-INFO}"

# 创建必要目录
mkdir -p "$POWERAUTOMATION_CONFIG_DIR"
mkdir -p "$POWERAUTOMATION_DATA_DIR"
mkdir -p "$POWERAUTOMATION_LOGS_DIR"
mkdir -p "$POWERAUTOMATION_CACHE_DIR"

# 输出配置信息
if [ "${MEMORY_RAG_DEBUG}" = "true" ]; then
    echo "🔧 PowerAutomation v4.71 Memory RAG Edition 环境配置"
    echo "📁 安装目录: $POWERAUTOMATION_HOME"
    echo "⚙️ 配置文件: $MEMORY_RAG_CONFIG"
    echo "📊 数据目录: $MEMORY_RAG_DATA_DIR"
    echo "📝 日志目录: $MEMORY_RAG_LOGS_DIR"
    echo "🚀 服务地址: http://$MEMORY_RAG_HOST:$MEMORY_RAG_PORT"
fi

