#!/bin/bash
# ClaudeEditor v4.6.7 簡化命令工具

echo "🚀 ClaudeEditor v4.6.7 已部署完成！"
echo "================================================"
echo ""
echo "📋 直接使用以下命令:"
echo ""
echo "🔧 主控制命令:"
echo "  python3 ~/.local/bin/claudeditor status"
echo "  python3 ~/.local/bin/claudeditor start"
echo ""
echo "📦 MCP組件控制:"
echo "  python3 ~/.local/bin/mcp codeflow status"
echo "  python3 ~/.local/bin/mcp xmasters solve \"問題描述\""
echo "  python3 ~/.local/bin/mcp operations monitor"
echo "  python3 ~/.local/bin/mcp security scan"
echo ""
echo "🔄 工作流控制:"
echo "  python3 ~/.local/bin/workflow list"
echo "  python3 ~/.local/bin/workflow start code_generation"
echo "  python3 ~/.local/bin/workflow start ui_design"
echo ""
echo "💡 快速測試 - 複製以下任一命令:"
echo ""
echo "python3 ~/.local/bin/claudeditor status"
echo ""
echo "python3 ~/.local/bin/workflow list"
echo ""
echo "python3 ~/.local/bin/mcp codeflow status"
echo ""
echo "================================================"