# PowerAutomation 工具整合配置
# 定義外部服務整合策略和參數

version: "1.0"
updated: "2025-01-18"

# 整合平台配置
platforms:
  mcp_so:
    name: "MCP.so"
    endpoint: "https://api.mcp.so/v1"
    authentication:
      type: "bearer"
      token_env: "MCP_API_TOKEN"
    capabilities:
      - code_analysis
      - documentation_generation
      - test_generation
      - dependency_analysis
    rate_limits:
      requests_per_minute: 60
      requests_per_day: 10000
    cost_model:
      base_cost: 0.001
      premium_features: 0.005
    
  aci_dev:
    name: "ACI.dev"
    endpoint: "https://api.aci.dev/v2"
    authentication:
      type: "api_key"
      key_env: "ACI_API_KEY"
    capabilities:
      - advanced_reasoning
      - knowledge_search
      - context_understanding
      - multi_modal_analysis
    rate_limits:
      requests_per_minute: 30
      tokens_per_day: 1000000
    cost_model:
      per_token: 0.00001
      minimum_charge: 0.001

  zapier:
    name: "Zapier"
    endpoint: "https://api.zapier.com/v1"
    authentication:
      type: "oauth2"
      client_id_env: "ZAPIER_CLIENT_ID"
      client_secret_env: "ZAPIER_CLIENT_SECRET"
    capabilities:
      - workflow_automation
      - data_synchronization
      - webhook_management
      - app_integration
    rate_limits:
      tasks_per_hour: 100
      zaps_per_month: 1000
    cost_model:
      per_task: 0.01
      subscription_tier: "professional"

# 工具映射規則
tool_mappings:
  # 代碼相關任務
  code_tasks:
    primary: "mcp_so"
    fallback: "local"
    capabilities_required:
      - code_analysis
      - documentation_generation
    
  # AI 推理任務
  ai_tasks:
    primary: "aci_dev"
    fallback: "mcp_so"
    capabilities_required:
      - advanced_reasoning
      - context_understanding
    
  # 自動化任務
  automation_tasks:
    primary: "zapier"
    fallback: "local"
    capabilities_required:
      - workflow_automation
      - app_integration

# 整合策略
integration_strategy:
  # 緩存策略
  caching:
    enabled: true
    ttl_seconds: 3600
    max_cache_size_mb: 100
    
  # 重試策略
  retry:
    max_attempts: 3
    backoff_strategy: "exponential"
    initial_delay_ms: 100
    max_delay_ms: 5000
    
  # 降級策略
  fallback:
    enabled: true
    health_check_interval: 60
    failure_threshold: 3
    recovery_time: 300
    
  # 成本控制
  cost_control:
    daily_budget: 50.0
    alert_threshold: 0.8
    auto_throttle: true
    
  # 性能優化
  performance:
    parallel_requests: 5
    timeout_seconds: 30
    connection_pool_size: 20

# 安全配置
security:
  # 數據保護
  data_protection:
    encrypt_in_transit: true
    encrypt_at_rest: true
    pii_detection: true
    pii_handling: "mask"
    
  # 訪問控制
  access_control:
    require_authentication: true
    api_key_rotation_days: 90
    ip_whitelist_enabled: false
    
  # 審計日誌
  audit_logging:
    enabled: true
    retention_days: 90
    include_request_details: true
    include_response_data: false

# 監控和告警
monitoring:
  # 指標收集
  metrics:
    enabled: true
    collection_interval: 60
    export_format: "prometheus"
    
  # 告警規則
  alerts:
    - name: "high_error_rate"
      condition: "error_rate > 0.05"
      severity: "critical"
      notification_channels: ["email", "slack"]
      
    - name: "budget_exceeded"
      condition: "daily_cost > daily_budget"
      severity: "warning"
      notification_channels: ["email"]
      
    - name: "slow_response"
      condition: "p95_latency > 5000"
      severity: "warning"
      notification_channels: ["slack"]

# 功能開關
feature_flags:
  enable_mcp_integration: true
  enable_aci_integration: true
  enable_zapier_integration: true
  enable_cost_optimization: true
  enable_smart_routing: true
  enable_predictive_caching: false
  enable_multi_region_failover: false

# 整合優先級
integration_priorities:
  - platform: "mcp_so"
    priority: 1
    reason: "Core development features"
    
  - platform: "aci_dev"
    priority: 2
    reason: "AI enhancement capabilities"
    
  - platform: "zapier"
    priority: 3
    reason: "Workflow automation"

# 成本優化規則
cost_optimization:
  # 批量處理
  batching:
    enabled: true
    max_batch_size: 50
    max_wait_time_ms: 1000
    
  # 智能路由
  smart_routing:
    consider_cost: true
    consider_latency: true
    consider_reliability: true
    weights:
      cost: 0.4
      latency: 0.3
      reliability: 0.3
      
  # 使用量預測
  usage_prediction:
    enabled: true
    model: "arima"
    forecast_days: 7
    
# 開發者體驗
developer_experience:
  # SDK 配置
  sdk:
    auto_retry: true
    debug_mode: false
    verbose_logging: false
    
  # 文檔和示例
  documentation:
    api_docs_url: "https://docs.powerautomation.ai/integrations"
    examples_repo: "https://github.com/powerautomation/integration-examples"
    
  # 測試環境
  testing:
    sandbox_enabled: true
    mock_responses: true
    test_credentials_provided: true